spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.ddl-auto: update
